[project]
name = "30daysofai-st"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "snowflake-snowpark-python>=1.44.0",
    "streamlit>=1.52.2",
]
